application: spendalyzer
version: 2013-01-17
runtime: python27
api_version: 1
threadsafe: true

  
libraries:
- name: jinja2
  version: latest


handlers:
- url: /.*
  script: spendalyzer.app
